#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://networkdb.crss46wugq83.ap-northeast-2.rds.amazonaws.com:3306/networkdb
#    username: root
#    password: Networkchat1!
#    thymeleaf:
#      cache: false
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: create